### ISSUE TITLE
Sniper Crosshairs

### ISSUE THREAD

**Issue by Zy0exe** [qbcore-framework/qb-weapons#1]
Sniper crosshairs do not work cuz of HideHudComponentThisFrame(14)

the fix i personally use is

```lua
Citizen.CreateThread(function()
    while true do
        if not IsAimCamActive() or not IsFirstPersonAimCamActive() then
            HideHudComponentThisFrame(14)
        end
        Citizen.Wait(0)
    end
end)
````

**Comment by JF9SpeNavK** [comment]
> Sniper crosshairs do not work cuz of HideHudComponentThisFrame(14)
> 
> the fix i personally use is
> 
> ```lua
> Citizen.CreateThread(function()
>     while true do
>         if not IsAimCamActive() or not IsFirstPersonAimCamActive() then
>             HideHudComponentThisFrame(14)
>         end
>         Citizen.Wait(0)
>     end
> end)
> ```

Sorry. where file add this code?
