### ISSUE TITLE
Weapon reload anim issue

### ISSUE THREAD

**Issue by ARSSANTO** [qbcore-framework/qb-weapons#104]
with the latest changes that new native just do anim if a weapon really need a ammo 

example i load 12 pistol ammo didn't shoot if i reload 2nd time to add more ammo its doesn't do animation if i shoot 1 time 1 bullet used then its doing reload anim hope i described that you guys can understand sorry for my bad english

**Comment by Sharkiiie** [comment]
Changing `MakePedReload(ped)` to `TaskReloadWeapon(ped)` seems to correct this.
