### ISSUE TITLE
Weapon repair not able to pick up when done

### ISSUE THREAD

**Issue by TheOldHook** [qbcore-framework/qb-weapons#106]
No errors, getting the mail when weapon ready for pickup. 
But no press 'E' to pick it up.

Only thing changed is location of the repairbench. 
Newest version.

**Comment by nukestarz** [comment]
This is my issue also.

**Comment by TheOldHook** [comment]
This was an easy fix, it seems like there is something with the time. 
In my case I wanted the repair to be instant since my repair cost prices are high, so I adjusted the repair time down. 

`weapons:server:RepairWeapon`
`local minute = 5 * 1`
