### ISSUE TITLE
[BUG] Weapon attachments mismatch

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-weapons#109]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Give yourself weapon_smg, smg_extendedmag or smg_drum. Equip gun and then use the attachment.

**Expected behavior**
Gun attachment attaches

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Latest
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
I think some of the weapons don't match up to attachments, including tints like luxuryfinish etc

**Comment by cowardtv** [comment]
anything new? since its the luxury finishes doesnt work for me but it seems to work on heavy pistol tho?

**Comment by cowardtv** [comment]
seems like only the Etched Wood Grip Finish saves
