### ISSUE TITLE
[BUG] Shooting spilled Jerry Can gas severely degrades weapon quality

### ISSUE THREAD

**Issue by rhapidfyre** [qbcore-framework/qb-weapons#111]
**Describe the bug**
When you pour gasoline on the ground with the Jerry Can, shooting it with a weapon causes extreme degradation of the weapon's quality. For example, firing off an entire magazine with a durability rate of 0.15 will cause slight wear and tear. However, using a brand new pistol with no damage to it's quality, shooting the gas results in nearly a 30% hit to the gun's durability.

**To Reproduce**
1. Acquire a Jerry Can
2. Pour gasoline on the ground
3. Shoot the gasoline trail
4. Observe the weapon's durability

**Expected behavior**
Shooting gasoline on the ground, a player/NPC or the sky should have the same degradation to the weapon's quality. Once the bullet leaves the barrel, the damage inflicted on the firearm is not based upon what the bullet impacts.

**Comment by LaserFeesh** [comment]
I noticed this also while messing around with refueling.
