### ISSUE TITLE
Weapon_Grenade Issue

### ISSUE THREAD

**Issue by DoomGuy524** [qbcore-framework/qb-weapons#115]
For every grenade type when you throw one, two get consumed if you have more than one in your inventory. I cannot find a fix I even spent time in the support channel with different developers and no one could find the root cause for this issue. It does it for weapon_grenade, weapon_smokegrenade, and weapon_bzgas. I'm sure it does others too but I only tested those three.

**Comment by sirhvd** [comment]
Easy fix, just increase the wait time @DoomGuy524 like this:
```
  if weapon and weapon ~= 0 and QBCore.Shared.Weapons[weapon] then
      QBCore.Functions.TriggerCallback('prison:server:checkThrowable', function(result)
          if result or GetAmmoInPedWeapon(ped, weapon) <= 0 then return end
          MultiplierAmount += 1
      end, weapon)

     -- checking weapon is throwable then wait for longer
      if QBCore.Shared.Weapons[weapon].weapontype == 'Throwable' then
          Wait(1000)
      else
          Wait(200)
      end
  end
```
