### ISSUE TITLE
[BUG] instant ammo from any vehicle

### ISSUE THREAD

**Issue by heyjeay** [qbcore-framework/qb-weapons#117]
**Describe the bug**
instant ammo while getting in and out of the vehicle, works with all weapons.

**To Reproduce**
1. Have your weapon out
2. Get into a vehicle
3.  Load up weapon with ammo
4. Shoot to deplete the magazine until it's run out completely
5. character will put away the weapon
6. get out of the vehicle
7. take out the same weapon
8. notice the depleted ammo is now back?

**Expected behavior**
Ammo is to be gone and set to 0.0 when you are leaving the vehicle instead it adds more as you take out the weapon.

**Screenshots**
No Screenshots

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? no Fresh Qbcore
 - Have you renamed `qb-` to something custom? No

**Comment by MannaMuncher** [comment]
This did not occur for me on a 5 star police raid, gun functioned normally.

**Comment by tom-osborne** [comment]
Not reproducible for me either.

Getting into a vehicle with gun out puts the gun away. Reloading and shooting all bullets in vehicle, then getting out of vehicle also puts gun away. Taking gun out again, still 0 bullets.

@heyjeay Can you test on a new fresh QBCore server and work out if you have any conflicting scripts. Please open a new issue if you still think there is a problem with the base QBCore. We might need a video to help us see the issue.
