### ISSUE TITLE
issue reloading

### ISSUE THREAD

**Issue by aristos86** [qbcore-framework/qb-weapons#119]
**Describe the bug**
I dont know if i explain it right but, after i reload any weapon, put back in the inventory, after i take it and handed it its comes not reloaded. any solution please

**Comment by GhzGarage** [comment]
Can you record a clip

**Comment by Wafflzdev** [comment]
@GhzGarage 

I am having this issues as well.  Just did a fresh install of QBCore on 8/9 and have not messed with anything weapons related scripts

Clip - https://medal.tv/games/gta-v/clips/w8iToJQemxfvU/d1337Y6xW59s?invite=cr-MSxHancsMzQyMTE4ODYs

**Comment by MannaMuncher** [comment]
You did not fill out the question template and this works correctly for me.

**Comment by tom-osborne** [comment]
Also tested and not reproducible. 

@Wafflzdev @aristos86 make sure you don't have any conflicting resources like a weapon holster script or something like that.
