### ISSUE TITLE
No Saving AMMO

### ISSUE THREAD

**Issue by Tajemniaczek** [qbcore-framework/qb-weapons#12]
Hello, I am writing because I have an error with fresh scripts, I use official inventory, etc ... Crashes in the console: SCRIPT ERROR: @ qb-weapons / server / main.lua: 15: attempt to perform arithmetic on a nil value (field 'ammo')
Also, have there been changes to DC? Because I didn't dc disappear. Please check Secret # 6399

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-weapons/commit/fcd923027e34b50134b6bef56d98cf55d135d3d0
