### ISSUE TITLE
[BUG] Repair Weapons

### ISSUE THREAD

**Issue by Kuwuz** [qbcore-framework/qb-weapons#121]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to '...' the weapon repair and try and repair a weapon
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
A clear and concise description of what you expected to happen. I expected my weapon to be repaired and it doesnt even take the money or weapon away. I get no errors from this at all, it just does nothing when i click E to repair

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] None
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

**Comment by MannaMuncher** [comment]
The weapon repair works correctly for me, Please delete the template question text from your response and fill in the question correctly.
