### ISSUE TITLE
[BUG] - Weapon reloading not saving ammo

### ISSUE THREAD

**Issue by Wafflzdev** [qbcore-framework/qb-weapons#125]
**Describe the bug**
When reloading a gun and putting it away and then taking it back out, the ammo that was just loaded is gone

**To Reproduce**
1. Pull out gun
2. Load ammo
3. Put gun away
4. Take gun back out

**Expected behavior**
Ammo should still be in gun

**Screenshots**
Clip - https://medal.tv/games/gta-v/clips/w8iToJQemxfvU/d1337Y6xW59s?invite=cr-MSxHancsMzQyMTE4ODYs

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Yesterday
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Lots of custom scripts, but the only ones that reference ammo are JDLogsV3, ps-fuel, keep-hunting, qb-admin (919), RageUI, Rex_MoneyWash, skm-stealshoes, cl_takehostage, Thinline_Glock
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

@GhzGarage

**Comment by Wafflzdev** [comment]
Issue appears to be related to ps-fuel.  I revered back to LegacyFuel this morning and no longer having the issue.  This part of the ps-fuel seems to be what is breaking it.

![image](https://user-images.githubusercontent.com/96218191/184127538-6fbc0b1b-3fb2-4ebf-9656-20f33d89bd2f.png)

**Comment by ChatDisabled** [comment]
As stated not a QBCore problem + just tested without issue. @Wafflzdev close the ticket?
