### ISSUE TITLE
[BUG] Weapons cannot be used

### ISSUE THREAD

**Issue by Wafflzdev** [qbcore-framework/qb-weapons#127]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to police armory or spawn in weapon thru admin menu
2. Access gun from inventory
3. Try and shoot

**Expected behavior**
Gun should shoot

**Screenshots**
![image](https://user-images.githubusercontent.com/96218191/185768163-02b67df0-20c9-4008-88d8-4b47d5891bd6.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]: Just installed QBCore today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] zDiscord and JDLogsV3
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

**Comment by tehface** [comment]
Having the same issue on a fresh install of qb... latest version pulled today

**Comment by CptNoHand** [comment]
Same issue here

**Comment by JogiTE** [comment]
Same issue here

**Comment by Wafflzdev** [comment]
So I have, to what I believe, resolved the issue.

- Go to qb\qb-weapons\client\main.lua
- Go to line 169
- Change code to say
if weapon == `WEAPON_UNARMED` then

- Save and restart

Just tested on my server and no issues and all weapons shoot now.

**Comment by ChatDisabled** [comment]
Refer too PR above. Also known as https://github.com/qbcore-framework/qb-inventory/pull/323

**Comment by Wafflzdev** [comment]
I just put that fix in place and also reverted my change in qb-weapons but the issue started happening again.  I will say with the fix of qb-inventory and my fix in qb-weapons, I have zero issues

**Comment by ChatDisabled** [comment]
In what way are you getting the weapon? Literally both `AddItem` function and `GiveItem` commands give no problems. If you however have some third party resource that is giving you a weapon with 0 quality eh. You also know that ALL existing weapons that you got when you didn't update need to be replaced. Their quality is still `nill`

**Comment by Wafflzdev** [comment]
I spawned weapon in from admin menu and also got a weapon from the police armory.  Both times same error.

**Comment by ChatDisabled** [comment]
PR above explains the itemshops behaviour, admin menu only uses the `AddItem` function and works fine for me though. Any other observations?

**Comment by Wafflzdev** [comment]
Tried guns from ammunation, armory and admin menu - all broke

**Comment by Wafflzdev** [comment]
I am on a fresh build

**Comment by ChatDisabled** [comment]
Literally quite impossible as per function [if no quality is set default to 100](https://github.com/qbcore-framework/qb-inventory/pull/324). Don't know more to say except works on my machine so mind getting more people to test this out?

**Comment by MannaMuncher** [comment]
This is also not occurring for me on admin give or police armory pickup.
