### ISSUE TITLE
Missing my Aiming Reticle from my server QBCore, anyone know how I can activate it back?! Idk how that happen. Never touched the weapons file.

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-weapons#133]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by xxUnknown13xx** [comment]
> 

Thank you so much!

**Comment by Striker-Qc** [comment]
look like the error is still there but we dont have HideHudComponentThisFrame(14) on line 16 for the latest release

**Comment by sklpz** [comment]
you can pretty much do the same, just delete "HideHudComponentThisFrame(!)" and it will work

**Comment by scottyus1** [comment]
> Go to `qb-smallresources > client > hudcomponents.lua` > line 16 where it says `HideHudComponentThisFrame(14)` and comment this line or remove it

Thank you :)
