### ISSUE TITLE
Weapons Not pulling out

### ISSUE THREAD

**Issue by Fear6682** [qbcore-framework/qb-weapons#134]
My Server had an error with qb-weapons so i redownloaded the script and now the guns don't work. They don't pull out it just appears with 'used'. There's also no animation it just does nothing. I've tried looking for setup guides but I can't find any. I'm gonna try re-adding the old qb-weapons resource and see if that works. If it doesn't I most likely will reply saying it doesn't work. I'll also try find the error we had before but we had to restart the server everytime we had it because a player that relogged would just get stuck on 'awaiting scripts'

**Comment by JordanBScott** [comment]
I am having the same issue and looking for a resolution ^^

**Comment by GGsolGG** [comment]
How do you access the old QB-Weapons ??
