### ISSUE TITLE
weapon ammo not loading

### ISSUE THREAD

**Issue by WarLikePrince** [qbcore-framework/qb-weapons#14]
qb-weapons/client/main.lua 144 attempt to index a nil value(field '?') error

**Comment by BerkieBb** [comment]
That's on your end, for support joing the QBCore discord: https://discord.gg/qbcore

**Comment by WarLikePrince** [comment]
Respected sir,
      Im unable to join the official server of qbcore framework. Kindly
support me to join.

**Comment by WarLikePrince** [comment]
Problem is solve now since updating with latest scripts from qbcore

**Comment by WarLikePrince** [comment]
But still need help with joining qbcore server . . . Kindly do need full if
you can . . . Or else can i get someone to contact on behalf of this issue

**Comment by BerkieBb** [comment]
@WarLikePrince we have a bot that doesn't allow people that are associated with fivem leaked discord servers in, you need to leave them all and make an appeal here: https://discord.gg/jeFeDRasfs

**Comment by WarLikePrince** [comment]
Thanks, I'll check it out. im removed from now such servers. now im not a
member of this type fo discord server . . and appealed on link you
mentioned above. what should be the next procedure

**Comment by BerkieBb** [comment]
If you've done an appeal and it gets accepted you can just join back https://discord.gg/qbcore

**Comment by WarLikePrince** [comment]
thanks a lot for helping me.
