### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-weapons#140]
Can't repair weapon at location When pressing "E". Nothing happens

**Comment by singh-manavv** [comment]
if you got any errors , please provide screenshot or some preview

**Comment by xxUnknown13xx** [comment]
https://streamable.com/n5ybzt

**Comment by Gangstaaaaa** [comment]
i just tried it worked for me if you're still having this issue try re updating qb-inventory also if you have qb-crafting its no longer a thing its combined with the inventory.

**Comment by xxUnknown13xx** [comment]
I just recently got QBCore through zap. I don't see the qb-crafting. That's odd that it works for you tho 👀

> i just tried it worked for me if you're still having this issue try re updating qb-inventory also if you have qb-crafting its no longer a thing its combined with the inventory.
