### ISSUE TITLE
[BUG] broken gun usable after using attachments

### ISSUE THREAD

**Issue by Goykz** [qbcore-framework/qb-weapons#141]
when a gun breaks and you take off any attachment or put one on the gun and it becomes usable again even if it shows health red and you get a pop up gun is broken spam while shooting.

**To Reproduce**
1. shot gun till it breaks
2. put on or remove attachment
3. shoot gun

![gg](https://user-images.githubusercontent.com/94883534/195720348-9bd2f272-53de-4764-85d5-7a8a998b0a64.jpeg)

**Comment by aga-001** [comment]
This bug fix or not.
