### ISSUE TITLE
attachments cant take from the weapon[BUG]

### ISSUE THREAD

**Issue by lukaswe97** [qbcore-framework/qb-weapons#144]
It is possible to put the Attachments on the Weapons but i can´t take them off the weapon ?

![20221111000322_1](https://user-images.githubusercontent.com/36117813/201224491-b91a82ab-05e6-4116-9e03-fb2713fa2e6a.jpg)
![20221111000332_1](https://user-images.githubusercontent.com/36117813/201224504-2984fd63-7213-44ed-b23e-b3078a0d2c23.jpg)

**Comment by Exyztence** [comment]
got the same issue, any fix for that?
