### ISSUE TITLE
SCRIPT ERROR: attempt to index a nil value

### ISSUE THREAD

**Issue by justinttw** [qbcore-framework/qb-weapons#15]
https://github.com/qbcore-framework/qb-weapons/blob/fcd923027e34b50134b6bef56d98cf55d135d3d0/client/main.lua#L125

Line 125 of the main client file in the qb-weapons folder returns an error when I try to add ammo to the weapon equipped to my ped. The if condition seems wrong as the weapon variable returns a hash key and not the name which would be expected in the shared lua in the QBCore resource.

**Comment by justinttw** [comment]
Found a simple fixed. Change QBCore.Shared.Weapons[weapon]["name"] ~= "weapon_unarmed" to CurrentWeaponData.name  and weapon to  CurrentWeaponData.name

**Comment by BerkieBb** [comment]
Make this a pull request with your changes instead
