### ISSUE TITLE
[BUG] The number of bullets does not appear

### ISSUE THREAD

**Issue by unknownentity1337** [qbcore-framework/qb-weapons#151]
The number of bullets in the weapon is not displayed on the top right corner of the screen, what is the problem

**Comment by djraymond** [comment]
replace this = disableHudComponents = {1, 2, 3, 4, 7, 9, 13, 14, 19, 20, 21, 22},

with this     disableHudComponents = {1, 2, 3, 4, 7, 9, 13, 14, 19, 20, 21},

in qb-smallresources/config line 93
