### ISSUE TITLE
Up to 30 FPS Loss While Using Weapons' Ironsight

### ISSUE THREAD

**Issue by thegambid** [qbcore-framework/qb-weapons#2]
Steps to reproduce:
1- Get a pistol on your hand.
2- Switch to first person view
3- Repeadetly spam the left click (shoot) button with ironsight. (How to open ironsight: While holding rightclick, use scroll up)

Not sure if the reason is about this script, it might be spamming bullet casings or something else as well.

**Comment by DmACKGL** [comment]
For some reason when you fire the weapon reloads all the chat suggestions 
![image](https://user-images.githubusercontent.com/10565361/122458399-c0f3d900-cf7d-11eb-8375-a30f738716dd.png)
Profiler: https://frontend.chrome-dev.tools/serve_rev/@901bcc219d9204748f9c256ceca0f2cd68061006/inspector.html?loadTimelineFromURL=https://gist.githubusercontent.com/DmACKGL/088398d257359c9b6f3794d6d1c5da59/raw/169dc9a9bc5462fdfecc39b91996a3f256ed1fc2/profileData.json%2520-%2520Weapon%2520Issue

**Comment by DmACKGL** [comment]
Trace:
https://github.com/qbcore-framework/qb-weapons/blob/71411aab63a246428f8f0739f0010f88db9fc60c/client/main.lua#L67
https://github.com/qbcore-framework/qb-core/blob/074dc307f33df4acbea33b317ab0f9d60a8ddb51/server/events.lua#L144
https://github.com/qbcore-framework/qb-core/blob/074dc307f33df4acbea33b317ab0f9d60a8ddb51/server/player.lua#L137
