### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by anhtuvn** [qbcore-framework/qb-weapons#29]
SCRIPT ERROR : @qb-weapon/server/main.lua:28: attempt to index a string value (field 'info')

**Comment by GhzGarage** [comment]
Just a random error line isn't telling me anything

**Comment by gringoDiaz** [comment]
I think issue with weapon ammo its not storing and it shows that error in console SCRIPT ERROR: @qb-weapons/server/main.lua:28: attempt to index a string value (field 'info')
