### ISSUE TITLE
This keeps breaking my server and I don't know how to fix it... 

### ISSUE THREAD

**Issue by B34R5M** [qbcore-framework/qb-weapons#30]
![image](https://user-images.githubusercontent.com/89864841/131583198-77d68907-97be-4f16-a2ce-06783f97cc0d.png)

**Comment by GhzGarage** [comment]
Update your resource?

**Comment by B34R5M** [comment]
I haven't ever touched it, this resource came from this github.

**Comment by GhzGarage** [comment]
I know said update it

**Comment by Holidayy95** [comment]
I also have this issue sometimes and I have to remove my player from the database to be able to spawn in. This only happens if the player has a weapon in their inventory though. It'll just happen randomly.

**Comment by hotatchanh** [comment]
> I know said update it

already updated but still got this issue

**Comment by BlacknGoldy** [comment]
having the same issue with updated version. any fix ? :)
