### ISSUE TITLE
SCRIPT ERROR: arithmetic on a nil value 

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-weapons#36]
SCRIPT ERROR: @qb-weapons/server/main.lua:83: attempt to perform arithmetic on a nil value (local 'DecreaseAmount')

**Comment by ihyajb** [comment]
more info? from what I understand is your trying to shoot a weapon without adding it to the qb-weapons config.

**Comment by Aspect1s** [comment]
@evanillaa did you find a fix for this, i'm having the same issue on my server. I know it's been several years since this has been open
