### ISSUE TITLE
Script error when trying to reload weapon

### ISSUE THREAD

**Issue by SepticLime** [qbcore-framework/qb-weapons#37]
- Errors
1.  @qb-weapons/client/main.lua:112: attempt to index a nil value (field '?')
2.  @qb-weapons/client/main.lua:32: attempt to index a nil value (field '?')

**Comment by ldlac** [comment]
In `qb-core/shared.lua` in the `QBShared.Weapons` table

Be sure that the keys as in "`" and it is not a string
