### ISSUE TITLE
Ammo problem

### ISSUE THREAD

**Issue by arieby** [qbcore-framework/qb-weapons#71]
When you press two weapons at the same moment from the inventory , the two weapons are filled with the same ammo that was for one weapon .

**Comment by arieby** [comment]
![545](https://user-images.githubusercontent.com/33897144/148695863-7139cf82-0413-4b80-aedb-7a5223a85cc1.png)

**Comment by Az210** [comment]
![téléchargement](https://user-images.githubusercontent.com/100566702/157998136-d8d2bf20-1fb6-41c8-ba26-d5e17b807db4.jpg)
