### ISSUE TITLE
new update error

### ISSUE THREAD

**Issue by Maureks** [qbcore-framework/qb-weapons#79]
hey , still giving the same error , even after the new update : 
@qb-weapons/config.lua:156: attempt to index a nil value (global 'LangWeapons')

what can I do ?

thanks for the attention

**Comment by Demo4889** [comment]
Did this issue occur after a server restart? or a script restart?

**Comment by Maureks** [comment]
I've updated both , qb-inventory and qb-weapons , and restarted the server.

qb-weapon is the only giving this error , 

This is the full lenght of the error : 

Error loading script @qb-weapons/config.lua in resource qb-inventory: @qb-weapons/config.lua:156: attempt to index a nil value (global 'LangWeapons')
[ script:qb-inventory] stack traceback:
[ script:qb-inventory] 	@qb-weapons/config.lua:156: in main chunk


qb-inventory works just fine, with no errors .

**Comment by Demo4889** [comment]
There are still some outstanding PR's waiting to be merged that may fix this issue, so bare with us. I will do some digging myself to see if I have any issues as well.

**Comment by Maureks** [comment]
For sure ! 
Thank you very much for the attention, and good luck ! Wish I could help !

Best regards!

**Comment by criticalrarex** [comment]
This one can be closed as it was resolved by Demos PR
