### ISSUE TITLE
License & Vehicle extra's

### ISSUE THREAD

**Issue by Qpanther0** [qbcore-framework/qb-weapons#91]
Hi Guys,

Allereerst hartelijk dank voor jullie contributie. Het is een waanzinnig mooi framework waar we met volle teugen van genieten.

Ik heb helaas een tweetal vragen waar ik tegen aan loop:

1. Waar kan ik de license store vinden voor men om wapens te kopen? dit kan ik nergens op de map vinden.
2. De extra's voor vehicles doet het niet: het verwijderen lukt wel, maar het terug plaatsen lukt niet: het geeft aan "voltooid" maar er gebeurd niks.

Kijk uit naar jullie reactie en blijf zo door gaan!

Voorbeeld: https://i.imgur.com/N8rRADX.jpg

**Comment by Demo4889** [comment]
Please use English when creating an issue, post your issues in the correct scripts issue area, or use the support channels in the discord.

Your first issue with not being able to find the weapon shops would be in qb-shops (check if you are actually running that script) and check the config on where those locations are set up.

Your second issue with the extras is in the qb-radialmenu. (We are aware of this issue)

**Comment by Qpanther0** [comment]
Hi Demo,

Sorry bout that, figured since the based is layed upon Dutch I figured giving in on some native language wouldn't harm.

The weapon shop shows as should, it's also running and I've never changed its config so they should be at the default locations. It's just the weapons license issue that when I try to purchase a gun it needs me to own the license which is nowhere to be bought/found.

**Comment by Demo4889** [comment]
It does exist. The police job has to grant you the ability to purchase a weapons license by using the grantlicense command while having the police job. Then the user has to go to the cityhall to purchase said license.

**Comment by Qpanther0** [comment]
Hi Demo,

Completely restarted the server and still unable to purchase any. Ironically when I try to give myself the license it does give me an error that I already own one. This server is straight out of the installer template not modified in anyway so far.. 

As for the car extra's maybe this helps: a different dev who made one for me a long time ago used the "reset" function on the car to force a refresh on it's appearance, causing the extra's to show up. Only downside would be a free restore of vehicle every time someone adds/removes an extra.

Example of license:
https://i.imgur.com/Tv3KauD.jpg
https://i.imgur.com/aGGJufH.jpg

**Comment by Demo4889** [comment]
Because you use the `/grantlicense` command, then go to the cityhall and purchase your weapons license. The grantlicense command doesn't actually give you the license, you have to go purchase it, as I stated in my comment above.

**Comment by Qpanther0** [comment]
My apologies I completely mis-read the stated above. 

It's working now, thank you. Just on a side-note: why does it require in-between interaction by the force? instead of allowing civs to purchase directly for themselfs

**Comment by Demo4889** [comment]
It's more of an RP thing. the `/grantlicense` command changes the metadata of the character for the person to be allowed to purchase a license, which then in turn can be used by the PD to check if a person has the authorization to have a weapons license. If the person has a license, but doesn't have the authorization to purchase a license, then their license would be an illegally obtained license, where they could be arrested for possessing an illegal weapons license.

**Comment by Qpanther0** [comment]
> It's more of an RP thing. the `/grantlicense` command changes the metadata of the character for the person to be allowed to purchase a license, which then in turn can be used by the PD to check if a person has the authorization to have a weapons license. If the person has a license, but doesn't have the authorization to purchase a license, then their license would be an illegally obtained license, where they could be arrested for possessing an illegal weapons license.

Seems like a good way of tracking indeed. Thanks for taking the time to answer my questions and for the help. I genuinely like qbcore a lot more than most available parties.

Stay safe and healthy, till next time!
