### ISSUE TITLE
gadget_parachute

### ISSUE THREAD

**Issue by Cupidojex** [qbcore-framework/qb-weapons#93]
There is no parachute item and I don't know how to add it to the server.

**Comment by SimpleOgi** [comment]
Hey,

You probably overlooked the fact that there is an item called parachute, which, when you use, equips a parachute, hope this helps

**Comment by Cupidojex** [comment]
Hello, I'm sorry but don't overlook it, it just doesn't work, I already
checked it

**Comment by Cupidojex** [comment]
and just to make sure, I have everything from qb but the black money
doesn't come out as an item in the inventory, could you help me?
