### ISSUE TITLE
Change weapon damage per item

### ISSUE THREAD

**Issue by P4R4NORM4L** [qbcore-framework/qb-weapons#97]
Is it possible to change the damage for individual items?,if so, How can I managed that ?

**Comment by GhzGarage** [comment]
You need a damage modifier meta file or script that modifies it in a loop

**Comment by P4R4NORM4L** [comment]
YEs figured it out thanks, Sorry for not updating my issue but here you can find all the metas for the weapons
https://github.com/P4R4NORM4L/snag_weapon_metas/tree/main/metas

**Comment by Xiantyl** [comment]
Where do i put the metas inside qb weapons?
